### ISSUE TITLE
An issue with mvn clean install exec:java

### ISSUE THREAD

**Issue by mccstan** [br4nd0n/spark-streaming#1]
That is the error i get when executing  : 

`
[mccstan@bmgs-soat spark-streaming]$ mvn clean install exec:java 
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building spark-example 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ spark-example ---
[INFO] Deleting /home/mccstan/Projects/demo_spark_redis_nodejs/spark-streaming/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ spark-example ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ spark-example ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ spark-example ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/mccstan/Projects/demo_spark_redis_nodejs/spark-streaming/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ spark-example ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ spark-example ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ spark-example ---
[INFO] Building jar: /home/mccstan/Projects/demo_spark_redis_nodejs/spark-streaming/target/spark-example-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ spark-example ---
[INFO] Installing /home/mccstan/Projects/demo_spark_redis_nodejs/spark-streaming/target/spark-example-1.0-SNAPSHOT.jar to /home/mccstan/.m2/repository/brandon-example/spark-example/1.0-SNAPSHOT/spark-example-1.0-SNAPSHOT.jar
[INFO] Installing /home/mccstan/Projects/demo_spark_redis_nodejs/spark-streaming/pom.xml to /home/mccstan/.m2/repository/brandon-example/spark-example/1.0-SNAPSHOT/spark-example-1.0-SNAPSHOT.pom
[INFO] 
[INFO] >>> exec-maven-plugin:1.2.1:java (default-cli) > validate @ spark-example >>>
[INFO] 
[INFO] <<< exec-maven-plugin:1.2.1:java (default-cli) < validate @ spark-example <<<
[INFO] 
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:java (default-cli) @ spark-example ---
[WARNING] 
java.lang.ClassNotFoundException: spark.example.SparkRunner
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:285)
	at java.lang.Thread.run(Thread.java:745)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.104 s
[INFO] Finished at: 2017-04-14T14:54:06+02:00
[INFO] Final Memory: 17M/208M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli) on project spark-example: An exception occured while executing the Java class. spark.example.SparkRunner -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

`

**Comment by mccstan** [comment]
I converted the project to a SBT project using maven dependancies : 
I was able to build using : 
`sbt compile`
I used this to run  :
`sbt run spark.streaming.SparkRunner`
